# Generated by Django 5.1.6 on 2025-02-14 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Compact', 'Compact'), ('Crossover', 'Crossover'), ('Premium', 'Premium')], max_length=50)),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energy_type', models.CharField(max_length=50)),
                ('gearbox', models.CharField(max_length=50)),
                ('extras', models.TextField(blank=True, null=True)),
                ('depot_location', models.CharField(default='Central Hub', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('reward_points', models.IntegerField(default=0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review_text', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_booking.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_spot', models.CharField(default='Same as pickup', max_length=100)),
                ('pickup_spot', models.CharField(default='Central Hub', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('Awaiting Confirmation', 'Awaiting Confirmation'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Awaiting Confirmation', max_length=25)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_booking.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardsProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulated_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('Debit Card', 'Debit Card'), ('Stripe', 'Stripe'), ('Mobile Pay', 'Mobile Pay')], max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_booking.reservation')),
            ],
        ),
    ]
